"""add_composite_indexes_and_optimize_json

Revision ID: 75bec4daca25
Revises: 
Create Date: 2025-11-01 19:38:33.481212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bec4daca25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comparison_cache_cleanup', 'comparison_cache', ['expires_at'], unique=False, postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.create_index('ix_comparisons_user_category_created', 'comparisons', ['user_id', 'category', 'created_at'], unique=False)
    op.create_index('ix_shared_comparisons_active', 'shared_comparisons', ['created_at'], unique=False, postgresql_where=sa.text("expires_at IS NULL OR expires_at > '2025-11-01 19:38:32.367344'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shared_comparisons_active', table_name='shared_comparisons', postgresql_where=sa.text("expires_at IS NULL OR expires_at > '2025-11-01 19:38:32.367344'"))
    op.drop_index('ix_comparisons_user_category_created', table_name='comparisons')
    op.drop_index('ix_comparison_cache_cleanup', table_name='comparison_cache', postgresql_where=sa.text('expires_at IS NOT NULL'))
    # ### end Alembic commands ###
